name: env_pytorch
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2021.7.5=h06a4308_1
  - certifi=2021.5.30=py38h06a4308_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1k=h27cfd23_0
  - pip=21.1.3=py38h06a4308_0
  - python=3.8.10=h12debd9_8
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py38h06a4308_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.13.0
    - aiohttp==3.7.4.post0
    - async-timeout==3.0.1
    - cachetools==4.2.2
    - chardet==4.0.0
    - charset-normalizer==2.0.4
    - configparser==5.0.2
    - cycler==0.10.0
    - datasetops==0.0.6
    - docker-pycreds==0.4.0
    - fsspec==2021.7.0
    - future==0.18.2
    - gitdb==4.0.7
    - gitpython==3.1.18
    - google-auth==1.34.0
    - google-auth-oauthlib==0.4.5
    - grpcio==1.39.0
    - idna==3.2
    - kiwisolver==1.3.1
    - markdown==3.3.4
    - matplotlib==3.4.2
    - multidict==5.1.0
    - oauthlib==3.1.1
    - office31==0.1.3
    - packaging==21.0
    - pandas==1.3.1
    - pathtools==0.1.2
    - pillow==8.3.1
    - promise==2.3
    - protobuf==3.17.3
    - psutil==5.8.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.1
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - pytorch-lightning==1.4.1
    - pytz==2021.1
    - pyyaml==5.4.1
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scipy==1.7.1
    - sentry-sdk==1.3.1
    - shortuuid==1.0.1
    - six==1.16.0
    - smmap==4.0.0
    - subprocess32==3.5.4
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - torchmetrics==0.4.1
    - tqdm==4.62.0
    - urllib3==1.26.6
    - wandb==0.11.2
    - werkzeug==2.0.1
    - yarl==1.6.3
prefix: /home/anirudh/anaconda3/envs/env_pytorch
