wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.2
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    t:
      1:
      - 1
      - 9
      2:
      - 1
      - 9
      4: 3.8.10
      5: 0.11.2
      8:
      - 5
